# Doublon pour s'assurer que la config est lue
spring.profiles.active=native
spring.application.name=ms_config_server
server.port=8888
spring.cloud.config.server.native.search-locations=classpath:/configs
spring.cloud.config.server.git.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/