# Application Name
spring.application.name=ms_eureka_server

# DÉSACTIVER LA VÉRIFICATION DE COMPATIBILITÉ (IMPORTANT)
spring.cloud.compatibility-verifier.enabled=false

# Port du serveur Eureka
server.port=8761

# Configuration Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuration du serveur
eureka.server.enable-self-preservation=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.response-cache-update-interval-ms=30000

# URL par défaut
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuration logging (optionnel)
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO